# --------------------------------------------------------------------
#  Core 
# --------------------------------------------------------------------
core:
  seed:           42
  out_dir:        outputs/

# --------------------------------------------------------------------
#  Data & preprocessing
# --------------------------------------------------------------------
data:
  dataset:        AMAZON_SALES                # {CIFAR‑10,CIFAR‑100,COCO,AMAZON,…}
  amazon_sales_path:    data/amazon_sales/1/amazon.csv
  amazon_sales_min_pos: 5
  amazon_sales_subset:  7_000                 # -1  ⇒ keep all rows
  reward_threshold: 4.0                 # rating > threshold → reward=1

# --------------------------------------------------------------------
#  Bandit & baseline settings
# --------------------------------------------------------------------
bandit:
  num_iterations: 1000                  # online visits
  max_items:      100
  baselines:                       # true → active
    abtest:     false
    ucb:        true
    thompson:   true
    epsilon:    false
    random:     false
  ucb_c:           2.0
  epsilon:         0.10

# --------------------------------------------------------------------
#  LLM judge (preference)
# --------------------------------------------------------------------
llm:
  model:         meta-llama/Llama-3.2-1B-Instruct
  device:        cuda:0
  temperature:   0.7                    # >0 → sampling, 0 → greedy
  bt_pairs:      20                     # pairs pe<r match‑up

# --------------------------------------------------------------------
#  GFlowNets section
# --------------------------------------------------------------------
gfn:
  latent_dim:     128
  hidden_dim:     256
  subset_size:      4
  batch_size:     128
  learning_rate: 1e-4
  entropy_coeff: 0.01

# --------------------------------------------------------------------
#  W&B
# --------------------------------------------------------------------
wandb:
  project:        BenchmarkRecSys
  run_name:       BenchmarkRecSys
  log_recs:       true